apiVersion: apps/v1
kind: Deployment
metadata:
  name: ashicloud01
spec:
  selector:
    matchLabels:
      app: ashicloud01-pod
  template:
    metadata:
      labels:
        app: ashicloud01-pod
    spec:
      containers:
      - name: ashicloud01-container
        image: barclaysacr02.azurecr.io/ashicloud:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
