name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_push_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag barclaysacr02.azurecr.io/ashicloud:latest
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: barclaysacr02
        # Container registry password
        password: AFnp+BILCUFnV9EuVTr9sxOBt/KqS=yU
        # Container registry server url
        login-server: barclaysacr02.azurecr.io
    - name: Push the Docker image
      run: docker push barclaysacr02.azurecr.io/ashicloud:latest
